[user]
# Add the name you want displayed in various areas of the Spotify app
displayName = 'RedwoodConf Attendee'

# Customize the device shown in the UI
[device]
name = "My Computer"

# valid types: 'computer', 'smartphone', 'speaker'
type = 'computer'
